# Generated by Django 4.2.7 on 2024-02-15 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_post_author_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='authorname',
            field=models.CharField(default='', max_length=100),
        ),
    ]
